import sys

sys.path.append("../camera-manage/")
sys.path.append("../colmap-manage/")

from colmap_manage.Module.colmap_manager import COLMAPManager
from colmap_manage.Module.dataset_manager import DatasetManager
from gaussian_splatting.Module.trainer import Trainer

data_folder_name = "NeRF/3vjia_simple"
data_folder_name = "NeRF/wine"
# data_folder_name = "UrbanScene3D/PolyTech_fine_zhang"
video_file_path = "/home/chli/chLi/Dataset/Video/wine.mp41"
down_sample_scale = 4
resolution = 1

scale = 1
show_image = False
print_progress = True
remove_old = False
remain_db = True
valid_percentage = 0.8
method_dict = {}

data_folder_path = "/home/chli/Dataset/" + data_folder_name + "/"
dataset_folder_path = (
    "../colmap-manage/output/" + data_folder_name.replace("/", "_") + "/"
)
output_folder_path = (
    "../gaussian-splatting/output/" + data_folder_name.replace("/", "_") + "/"
)
image_folder_name = "images"
device = "cuda"
iterations = 300000
port = 6007
percentent_dense = 0.01

COLMAPManager(
    data_folder_path, video_file_path, down_sample_scale, print_progress=False
).autoGenerateData(remove_old, remain_db, valid_percentage)
DatasetManager().generateDataset(
    "gs", data_folder_path, dataset_folder_path, method_dict
)

Trainer(
    dataset_folder_path + "gs/",
    output_folder_path,
    resolution,
    iterations,
    port,
    percentent_dense,
).train()
