import sys

sys.path.append("../colmap-manage/")

from colmap_manage.Module.colmap_manager import COLMAPManager
from colmap_manage.Module.dataset_manager import DatasetManager

data_folder_path = "/home/chli/Dataset/UrbanScene3D/PolyTech_fine/"
video_file_path = "None"
down_sample_scale = 4

scale = 1
show_image = False
print_progress = True
remove_old = False
valid_percentage = 0.8
dataset_folder_path = "../colmap-manage/output/PolyTech_fine/"
method_dict = {}

COLMAPManager(data_folder_path, video_file_path).autoGenerateData(
    remove_old, valid_percentage
)
DatasetManager().generateDataset(
    "gs", data_folder_path, dataset_folder_path, method_dict
)
