TRAIN_CONFIG = {
    'dataset_folder_path': '../colmap-manage/output/NeRF_3vjia_simple/gs/',
    'output_folder_path': '../gaussian-splatting/output/NeRF_3vjia_simple/',
    'start_checkpoint': None,
    'iterations': 40000,
    'resolution': 8,
    'ip': '127.0.0.1',
    'port': 6006,
    'device': 'cuda',
    'percent_dense': 0.01,
    'detect_anomaly': False,
    'test_iterations': [7000, 30000, 40000],
    'save_iterations': [7000, 30000, 40000],
    'checkpoint_iterations': [],
    'quiet': False,
}
